// file yarefpersys/primes_yrps.c
// SPDX-License-Identifier: GPL-3.0-or-later

/***
 * License:
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 ****/
#include "yrps.h"

const char primes_yrps_id[] = YRPS_ID;

// primes up to 7516192768, growing with 3, using primes, pid 381921
//// piping primes 2 7516192768
// data was generated by makeprimes.c on github.com/bstarynk/misc-basile
// running makeprimes $[7<<30] 3 
const int64_t primes_yrps[] = {
  2, 3, 5, 7,
  11, 17, 23, 31,
  43, 59, 79, 107,
  149, 199, 269, 359,
  479, 641, 857, 1151,
  1543, 2063, 2753, 3671,
  4903, 6547, 8731, 11657,
  15551, 20743, 27673, 36899,
  49199, 65599, 87473, 116639,
  155521, 207367, 276499, 368689,
  491591, 655471, 873979, 1165349,
  1553803, 2071753, 2762339, 3683143,
  4910887, 6547859, 8730487, 11640677,
  15520909, 20694571, 27592771, 36790373,
  49053859, 65405161, 87206887, 116275871,
  155034499, 206712703, 275616947, 367489301,
  489985739, 653314339, 871085819, 1161447799,
  1548597073, 2064796109, 2753061491, 3670748671,
  4894331573, 6525775439,
  0                             /// terminating zero added manually
};


int64_t
yrps_prime_above (int64_t l)
{
  const unsigned numprimes = sizeof (primes_yrps) / sizeof (primes_yrps[0]);
  if (l <= 2)
    return 3;
  if (l >= primes_yrps[numprimes - 1])
    return 0;
  int lo = 0, hi = numprimes;
  while (lo + 5 < hi)
    {
      int md = (lo + hi) / 2;
      if (primes_yrps[md] > l)
        hi = md;
      else
        lo = md;
    };
  if (hi < (int) numprimes - 1)
    hi++;
  if (hi < (int) numprimes - 1)
    hi++;
  for (int ix = lo; ix < hi; ix++)
    if (primes_yrps[ix] > l)
      return primes_yrps[ix];
  return 0;
}                               /* end yrps_prime_above */

int64_t
yrps_prime_below (int64_t l)
{
  const unsigned numprimes = sizeof (primes_yrps) / sizeof (primes_yrps[0]);
  int lo = 0, hi = numprimes;
  if (l >= primes_yrps[numprimes - 1])
    return 0;
  if (l < 2)
    return 2;
  while (lo + 5 < hi)
    {
      int md = (lo + hi) / 2;
      if (primes_yrps[md] > l)
        hi = md;
      else
        lo = md;
    };
  if (hi < (int) numprimes - 1)
    hi++;
  if (hi < (int) numprimes - 1)
    hi++;
  for (int ix = hi; ix >= 0; ix--)
    if (primes_yrps[ix] < l)
      return primes_yrps[ix];
  return 0;
}                               /* end yrps_prime_below */

int64_t
yrps_prime_of_rank (int rk)
{
  const unsigned numprimes = sizeof (primes_yrps) / sizeof (primes_yrps[0]);
  if (rk < 0)
    return 0;
  if (rk < (int) numprimes)
    return primes_yrps[rk];
  return 0;
}                               // end of yrps_prime_of_rank

int
yrps_rank_of_prime (int64_t prim)
{
  const unsigned numprimes = sizeof (primes_yrps) / sizeof (primes_yrps[0]);
  if (prim < 0 || (prim % 2 == 0) || (prim % 3 == 0)
      || (prim % 5 == 0) || prim > primes_yrps[numprimes - 1])
    return -1;
  int lo = 0, hi = numprimes;
  while (lo + 5 < hi)
    {
      int md = (lo + hi) / 2;
      if (primes_yrps[md] > lo)
        hi = md;
      else
        lo = md;
    }
  for (int ix = lo; ix < hi; ix++)
    if (primes_yrps[ix] == prim)
      return ix;
  return -1;
}                               /* end yrps_rank_of_prime */


/// end of file yarefpersys/primes_yrps.c
